/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as PrimeShellRouteImport } from './routes/prime/_shell'
import { Route as PrimeLoginRouteImport } from './routes/prime/login'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as AdminShellContaRouteImport } from './routes/admin/_shell/conta'
import { Route as AdminShellMembrosRouteImport } from './routes/admin/_shell/membros'
import { Route as ApiRadarPublishRouteImport } from './routes/api/radar/publish'
import { Route as ApiRadarUploadImageRouteImport } from './routes/api/radar/upload-image'
import { Route as PrimeShellIndexRouteImport } from './routes/prime/_shell/index'
import { Route as PrimeShellCalculadoraRouteImport } from './routes/prime/_shell/calculadora'
import { Route as PrimeShellContaRouteImport } from './routes/prime/_shell/conta'
import { Route as AdminShellGarimposIndexRouteImport } from './routes/admin/_shell/garimpos.index'
import { Route as AdminShellGarimposIdRouteImport } from './routes/admin/_shell/garimpos.$id'
import { Route as ApiPublicRadarHealthRouteImport } from './routes/api/public/radar/health'
import { Route as ApiPublicRadarPublishRouteImport } from './routes/api/public/radar/publish'
import { Route as ApiPublicRadarUploadImageRouteImport } from './routes/api/public/radar/upload-image'
import { Route as PrimeShellConteudosIndexRouteImport } from './routes/prime/_shell/conteudos.index'
import { Route as PrimeShellConteudosSlugRouteImport } from './routes/prime/_shell/conteudos.$slug'
import { Route as PrimeShellGarimposIndexRouteImport } from './routes/prime/_shell/garimpos.index'
import { Route as PrimeShellGarimposIdRouteImport } from './routes/prime/_shell/garimpos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeShellRoute = PrimeShellRouteImport.update({
  id: '/prime/_shell',
  path: '/prime',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeLoginRoute = PrimeLoginRouteImport.update({
  id: '/prime/login',
  path: '/prime/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellContaRoute = AdminShellContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellMembrosRoute = AdminShellMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AdminShellRoute,
} as any)
const ApiRadarPublishRoute = ApiRadarPublishRouteImport.update({
  id: '/api/radar/publish',
  path: '/api/radar/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarUploadImageRoute = ApiRadarUploadImageRouteImport.update({
  id: '/api/radar/upload-image',
  path: '/api/radar/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeShellIndexRoute = PrimeShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrimeShellRoute,
} as any)
const PrimeShellCalculadoraRoute = PrimeShellCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => PrimeShellRoute,
} as any)
const PrimeShellContaRoute = PrimeShellContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => PrimeShellRoute,
} as any)
const AdminShellGarimposIndexRoute = AdminShellGarimposIndexRouteImport.update({
  id: '/garimpos/',
  path: '/garimpos/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellGarimposIdRoute = AdminShellGarimposIdRouteImport.update({
  id: '/garimpos/$id',
  path: '/garimpos/$id',
  getParentRoute: () => AdminShellRoute,
} as any)
const ApiPublicRadarHealthRoute = ApiPublicRadarHealthRouteImport.update({
  id: '/api/public/radar/health',
  path: '/api/public/radar/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarPublishRoute = ApiPublicRadarPublishRouteImport.update({
  id: '/api/public/radar/publish',
  path: '/api/public/radar/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarUploadImageRoute =
  ApiPublicRadarUploadImageRouteImport.update({
    id: '/api/public/radar/upload-image',
    path: '/api/public/radar/upload-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrimeShellConteudosIndexRoute =
  PrimeShellConteudosIndexRouteImport.update({
    id: '/conteudos/',
    path: '/conteudos/',
    getParentRoute: () => PrimeShellRoute,
  } as any)
const PrimeShellConteudosSlugRoute = PrimeShellConteudosSlugRouteImport.update({
  id: '/conteudos/$slug',
  path: '/conteudos/$slug',
  getParentRoute: () => PrimeShellRoute,
} as any)
const PrimeShellGarimposIndexRoute = PrimeShellGarimposIndexRouteImport.update({
  id: '/garimpos/',
  path: '/garimpos/',
  getParentRoute: () => PrimeShellRoute,
} as any)
const PrimeShellGarimposIdRoute = PrimeShellGarimposIdRouteImport.update({
  id: '/garimpos/$id',
  path: '/garimpos/$id',
  getParentRoute: () => PrimeShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/prime': typeof PrimeShellRouteWithChildren
  '/prime/login': typeof PrimeLoginRoute
  '/admin/conta': typeof AdminShellContaRoute
  '/admin/membros': typeof AdminShellMembrosRoute
  '/api/radar/publish': typeof ApiRadarPublishRoute
  '/api/radar/upload-image': typeof ApiRadarUploadImageRoute
  '/prime/calculadora': typeof PrimeShellCalculadoraRoute
  '/prime/conta': typeof PrimeShellContaRoute
  '/admin/': typeof AdminShellIndexRoute
  '/prime/': typeof PrimeShellIndexRoute
  '/admin/garimpos/$id': typeof AdminShellGarimposIdRoute
  '/api/public/radar/health': typeof ApiPublicRadarHealthRoute
  '/api/public/radar/publish': typeof ApiPublicRadarPublishRoute
  '/api/public/radar/upload-image': typeof ApiPublicRadarUploadImageRoute
  '/prime/conteudos/$slug': typeof PrimeShellConteudosSlugRoute
  '/prime/garimpos/$id': typeof PrimeShellGarimposIdRoute
  '/admin/garimpos/': typeof AdminShellGarimposIndexRoute
  '/prime/conteudos/': typeof PrimeShellConteudosIndexRoute
  '/prime/garimpos/': typeof PrimeShellGarimposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/prime/login': typeof PrimeLoginRoute
  '/admin/conta': typeof AdminShellContaRoute
  '/admin/membros': typeof AdminShellMembrosRoute
  '/api/radar/publish': typeof ApiRadarPublishRoute
  '/api/radar/upload-image': typeof ApiRadarUploadImageRoute
  '/prime/calculadora': typeof PrimeShellCalculadoraRoute
  '/prime/conta': typeof PrimeShellContaRoute
  '/admin': typeof AdminShellIndexRoute
  '/prime': typeof PrimeShellIndexRoute
  '/admin/garimpos/$id': typeof AdminShellGarimposIdRoute
  '/api/public/radar/health': typeof ApiPublicRadarHealthRoute
  '/api/public/radar/publish': typeof ApiPublicRadarPublishRoute
  '/api/public/radar/upload-image': typeof ApiPublicRadarUploadImageRoute
  '/prime/conteudos/$slug': typeof PrimeShellConteudosSlugRoute
  '/prime/garimpos/$id': typeof PrimeShellGarimposIdRoute
  '/admin/garimpos': typeof AdminShellGarimposIndexRoute
  '/prime/conteudos': typeof PrimeShellConteudosIndexRoute
  '/prime/garimpos': typeof PrimeShellGarimposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/prime/_shell': typeof PrimeShellRouteWithChildren
  '/prime/login': typeof PrimeLoginRoute
  '/admin/_shell/conta': typeof AdminShellContaRoute
  '/admin/_shell/membros': typeof AdminShellMembrosRoute
  '/api/radar/publish': typeof ApiRadarPublishRoute
  '/api/radar/upload-image': typeof ApiRadarUploadImageRoute
  '/prime/_shell/calculadora': typeof PrimeShellCalculadoraRoute
  '/prime/_shell/conta': typeof PrimeShellContaRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/prime/_shell/': typeof PrimeShellIndexRoute
  '/admin/_shell/garimpos/$id': typeof AdminShellGarimposIdRoute
  '/api/public/radar/health': typeof ApiPublicRadarHealthRoute
  '/api/public/radar/publish': typeof ApiPublicRadarPublishRoute
  '/api/public/radar/upload-image': typeof ApiPublicRadarUploadImageRoute
  '/prime/_shell/conteudos/$slug': typeof PrimeShellConteudosSlugRoute
  '/prime/_shell/garimpos/$id': typeof PrimeShellGarimposIdRoute
  '/admin/_shell/garimpos/': typeof AdminShellGarimposIndexRoute
  '/prime/_shell/conteudos/': typeof PrimeShellConteudosIndexRoute
  '/prime/_shell/garimpos/': typeof PrimeShellGarimposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/prime'
    | '/prime/login'
    | '/admin/conta'
    | '/admin/membros'
    | '/api/radar/publish'
    | '/api/radar/upload-image'
    | '/prime/calculadora'
    | '/prime/conta'
    | '/admin/'
    | '/prime/'
    | '/admin/garimpos/$id'
    | '/api/public/radar/health'
    | '/api/public/radar/publish'
    | '/api/public/radar/upload-image'
    | '/prime/conteudos/$slug'
    | '/prime/garimpos/$id'
    | '/admin/garimpos/'
    | '/prime/conteudos/'
    | '/prime/garimpos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/login'
    | '/prime/login'
    | '/admin/conta'
    | '/admin/membros'
    | '/api/radar/publish'
    | '/api/radar/upload-image'
    | '/prime/calculadora'
    | '/prime/conta'
    | '/admin'
    | '/prime'
    | '/admin/garimpos/$id'
    | '/api/public/radar/health'
    | '/api/public/radar/publish'
    | '/api/public/radar/upload-image'
    | '/prime/conteudos/$slug'
    | '/prime/garimpos/$id'
    | '/admin/garimpos'
    | '/prime/conteudos'
    | '/prime/garimpos'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/admin/_shell'
    | '/admin/login'
    | '/prime/_shell'
    | '/prime/login'
    | '/admin/_shell/conta'
    | '/admin/_shell/membros'
    | '/api/radar/publish'
    | '/api/radar/upload-image'
    | '/prime/_shell/calculadora'
    | '/prime/_shell/conta'
    | '/admin/_shell/'
    | '/prime/_shell/'
    | '/admin/_shell/garimpos/$id'
    | '/api/public/radar/health'
    | '/api/public/radar/publish'
    | '/api/public/radar/upload-image'
    | '/prime/_shell/conteudos/$slug'
    | '/prime/_shell/garimpos/$id'
    | '/admin/_shell/garimpos/'
    | '/prime/_shell/conteudos/'
    | '/prime/_shell/garimpos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  PrimeShellRoute: typeof PrimeShellRouteWithChildren
  PrimeLoginRoute: typeof PrimeLoginRoute
  ApiRadarPublishRoute: typeof ApiRadarPublishRoute
  ApiRadarUploadImageRoute: typeof ApiRadarUploadImageRoute
  ApiPublicRadarHealthRoute: typeof ApiPublicRadarHealthRoute
  ApiPublicRadarPublishRoute: typeof ApiPublicRadarPublishRoute
  ApiPublicRadarUploadImageRoute: typeof ApiPublicRadarUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime/_shell': {
      id: '/prime/_shell'
      path: '/prime'
      fullPath: '/prime'
      preLoaderRoute: typeof PrimeShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime/login': {
      id: '/prime/login'
      path: '/prime/login'
      fullPath: '/prime/login'
      preLoaderRoute: typeof PrimeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/conta': {
      id: '/admin/_shell/conta'
      path: '/conta'
      fullPath: '/admin/conta'
      preLoaderRoute: typeof AdminShellContaRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/membros': {
      id: '/admin/_shell/membros'
      path: '/membros'
      fullPath: '/admin/membros'
      preLoaderRoute: typeof AdminShellMembrosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/api/radar/publish': {
      id: '/api/radar/publish'
      path: '/api/radar/publish'
      fullPath: '/api/radar/publish'
      preLoaderRoute: typeof ApiRadarPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar/upload-image': {
      id: '/api/radar/upload-image'
      path: '/api/radar/upload-image'
      fullPath: '/api/radar/upload-image'
      preLoaderRoute: typeof ApiRadarUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime/_shell/': {
      id: '/prime/_shell/'
      path: '/'
      fullPath: '/prime/'
      preLoaderRoute: typeof PrimeShellIndexRouteImport
      parentRoute: typeof PrimeShellRoute
    }
    '/prime/_shell/calculadora': {
      id: '/prime/_shell/calculadora'
      path: '/calculadora'
      fullPath: '/prime/calculadora'
      preLoaderRoute: typeof PrimeShellCalculadoraRouteImport
      parentRoute: typeof PrimeShellRoute
    }
    '/prime/_shell/conta': {
      id: '/prime/_shell/conta'
      path: '/conta'
      fullPath: '/prime/conta'
      preLoaderRoute: typeof PrimeShellContaRouteImport
      parentRoute: typeof PrimeShellRoute
    }
    '/admin/_shell/garimpos/': {
      id: '/admin/_shell/garimpos/'
      path: '/garimpos'
      fullPath: '/admin/garimpos/'
      preLoaderRoute: typeof AdminShellGarimposIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/garimpos/$id': {
      id: '/admin/_shell/garimpos/$id'
      path: '/garimpos/$id'
      fullPath: '/admin/garimpos/$id'
      preLoaderRoute: typeof AdminShellGarimposIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/api/public/radar/health': {
      id: '/api/public/radar/health'
      path: '/api/public/radar/health'
      fullPath: '/api/public/radar/health'
      preLoaderRoute: typeof ApiPublicRadarHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/publish': {
      id: '/api/public/radar/publish'
      path: '/api/public/radar/publish'
      fullPath: '/api/public/radar/publish'
      preLoaderRoute: typeof ApiPublicRadarPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/upload-image': {
      id: '/api/public/radar/upload-image'
      path: '/api/public/radar/upload-image'
      fullPath: '/api/public/radar/upload-image'
      preLoaderRoute: typeof ApiPublicRadarUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime/_shell/conteudos/': {
      id: '/prime/_shell/conteudos/'
      path: '/conteudos'
      fullPath: '/prime/conteudos/'
      preLoaderRoute: typeof PrimeShellConteudosIndexRouteImport
      parentRoute: typeof PrimeShellRoute
    }
    '/prime/_shell/conteudos/$slug': {
      id: '/prime/_shell/conteudos/$slug'
      path: '/conteudos/$slug'
      fullPath: '/prime/conteudos/$slug'
      preLoaderRoute: typeof PrimeShellConteudosSlugRouteImport
      parentRoute: typeof PrimeShellRoute
    }
    '/prime/_shell/garimpos/': {
      id: '/prime/_shell/garimpos/'
      path: '/garimpos'
      fullPath: '/prime/garimpos/'
      preLoaderRoute: typeof PrimeShellGarimposIndexRouteImport
      parentRoute: typeof PrimeShellRoute
    }
    '/prime/_shell/garimpos/$id': {
      id: '/prime/_shell/garimpos/$id'
      path: '/garimpos/$id'
      fullPath: '/prime/garimpos/$id'
      preLoaderRoute: typeof PrimeShellGarimposIdRouteImport
      parentRoute: typeof PrimeShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellContaRoute: typeof AdminShellContaRoute
  AdminShellMembrosRoute: typeof AdminShellMembrosRoute
  AdminShellIndexRoute: typeof AdminShellIndexRoute
  AdminShellGarimposIdRoute: typeof AdminShellGarimposIdRoute
  AdminShellGarimposIndexRoute: typeof AdminShellGarimposIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellContaRoute: AdminShellContaRoute,
  AdminShellMembrosRoute: AdminShellMembrosRoute,
  AdminShellIndexRoute: AdminShellIndexRoute,
  AdminShellGarimposIdRoute: AdminShellGarimposIdRoute,
  AdminShellGarimposIndexRoute: AdminShellGarimposIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface PrimeShellRouteChildren {
  PrimeShellCalculadoraRoute: typeof PrimeShellCalculadoraRoute
  PrimeShellContaRoute: typeof PrimeShellContaRoute
  PrimeShellIndexRoute: typeof PrimeShellIndexRoute
  PrimeShellConteudosSlugRoute: typeof PrimeShellConteudosSlugRoute
  PrimeShellGarimposIdRoute: typeof PrimeShellGarimposIdRoute
  PrimeShellConteudosIndexRoute: typeof PrimeShellConteudosIndexRoute
  PrimeShellGarimposIndexRoute: typeof PrimeShellGarimposIndexRoute
}

const PrimeShellRouteChildren: PrimeShellRouteChildren = {
  PrimeShellCalculadoraRoute: PrimeShellCalculadoraRoute,
  PrimeShellContaRoute: PrimeShellContaRoute,
  PrimeShellIndexRoute: PrimeShellIndexRoute,
  PrimeShellConteudosSlugRoute: PrimeShellConteudosSlugRoute,
  PrimeShellGarimposIdRoute: PrimeShellGarimposIdRoute,
  PrimeShellConteudosIndexRoute: PrimeShellConteudosIndexRoute,
  PrimeShellGarimposIndexRoute: PrimeShellGarimposIndexRoute,
}

const PrimeShellRouteWithChildren = PrimeShellRoute._addFileChildren(
  PrimeShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  PrimeShellRoute: PrimeShellRouteWithChildren,
  PrimeLoginRoute: PrimeLoginRoute,
  ApiRadarPublishRoute: ApiRadarPublishRoute,
  ApiRadarUploadImageRoute: ApiRadarUploadImageRoute,
  ApiPublicRadarHealthRoute: ApiPublicRadarHealthRoute,
  ApiPublicRadarPublishRoute: ApiPublicRadarPublishRoute,
  ApiPublicRadarUploadImageRoute: ApiPublicRadarUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
