/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRadarPublishRouteImport } from './routes/api/public/radar/publish'
import { Route as ApiPublicRadarUploadImageRouteImport } from './routes/api/public/radar/upload-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarPublishRoute = ApiPublicRadarPublishRouteImport.update({
  id: '/api/public/radar/publish',
  path: '/api/public/radar/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarUploadImageRoute =
  ApiPublicRadarUploadImageRouteImport.update({
    id: '/api/public/radar/upload-image',
    path: '/api/public/radar/upload-image',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/radar/publish': typeof ApiPublicRadarPublishRoute
  '/api/public/radar/upload-image': typeof ApiPublicRadarUploadImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/radar/publish': typeof ApiPublicRadarPublishRoute
  '/api/public/radar/upload-image': typeof ApiPublicRadarUploadImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/radar/publish': typeof ApiPublicRadarPublishRoute
  '/api/public/radar/upload-image': typeof ApiPublicRadarUploadImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/radar/publish' | '/api/public/radar/upload-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/radar/publish' | '/api/public/radar/upload-image'
  id:
    | '__root__'
    | '/'
    | '/api/public/radar/publish'
    | '/api/public/radar/upload-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicRadarPublishRoute: typeof ApiPublicRadarPublishRoute
  ApiPublicRadarUploadImageRoute: typeof ApiPublicRadarUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/publish': {
      id: '/api/public/radar/publish'
      path: '/api/public/radar/publish'
      fullPath: '/api/public/radar/publish'
      preLoaderRoute: typeof ApiPublicRadarPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/upload-image': {
      id: '/api/public/radar/upload-image'
      path: '/api/public/radar/upload-image'
      fullPath: '/api/public/radar/upload-image'
      preLoaderRoute: typeof ApiPublicRadarUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicRadarPublishRoute: ApiPublicRadarPublishRoute,
  ApiPublicRadarUploadImageRoute: ApiPublicRadarUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
